# Generated by Django 5.0.3 on 2024-05-07 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_remove_generalnotification_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='generalnotification',
            options={'ordering': ['-created_at']},
        ),
    ]
