# Generated by Django 5.0.3 on 2024-05-02 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_chefprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('regular', 'Regular'), ('Chef', 'Chef')], default='regular', max_length=255, verbose_name='Account Type'),
        ),
    ]
