# Generated by Django 5.0.3 on 2024-05-02 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_following'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('regular', 'Regular'), ('chef', 'Chef')], default='regular', max_length=255, verbose_name='Account Type'),
        ),
    ]
