# Generated by Django 5.0.3 on 2024-05-02 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_account_type'),
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('video', models.FileField(upload_to='recipes/')),
                ('chef_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='accounts.chefprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('measurement', models.CharField(choices=[('g', 'Grams'), ('kg', 'Kilograms'), ('ml', 'Milliliters'), ('l', 'Liters'), ('tsp', 'Teaspoon'), ('tbsp', 'Tablespoon'), ('cup', 'Cup'), ('pint', 'Pint'), ('quart', 'Quart'), ('gallon', 'Gallon'), ('oz', 'Ounce'), ('lb', 'Pound')], max_length=20)),
                ('cuisine', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='recipes.cuisine')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='recipes.recipe')),
            ],
        ),
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin', models.TimeField()),
                ('end', models.TimeField()),
                ('description', models.TextField()),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directions', to='recipes.recipe')),
            ],
        ),
        migrations.CreateModel(
            name='CookBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('regular_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cookbooks', to='accounts.profile')),
                ('recipes', models.ManyToManyField(related_name='cookbooks', to='recipes.recipe')),
            ],
        ),
    ]
