# Generated by Django 5.0.3 on 2024-05-04 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_alter_recipe_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discussion',
            name='replies',
        ),
        migrations.AddField(
            model_name='discussion',
            name='replied_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='recipes.discussion'),
        ),
    ]
